mptcp: Fix build with PROC_FS disabled.
net/mptcp/subflow.c: In function ‘mptcp_subflow_create_socket’:
net/mptcp/subflow.c:624:25: error: ‘struct netns_core’ has no member named ‘sock_inuse’

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit f6f7d8cf55348751cc8a5f40c8f9835ee1752df4)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>